### ISSUE TITLE
Need of a more comprehensive README

### ISSUE THREAD

**Issue by L04DB4L4NC3R** [mayankkumar2/VIT-RM-Organizer#1]
I was on a lookout for something like this. So glad that someone is doing it. Would be cool to add the following features in the `README.md` as well:

- Demo video/gif of how the script actually works
- Constraints
- Future features to be added (if any, suggestions might be to sort material according to time)

See the [markdown cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) for the same.

There is already a chrome extension which does this, would love if there can be a firefox addon also.

**Comment by mayankkumar2** [comment]
Thank you for your interest.

I have added a gif file regarding how to use the script for Linux users, I will soon add the same for the Windows users as well. I've tried to resolve most of the issues you have mentioned.

I will be working on making a firefox addon on a separate repository very soon.

**Comment by L04DB4L4NC3R** [comment]
This issue can be closed now
